### ISSUE TITLE
header navigation is cut

### ISSUE THREAD

**Issue by aiedev** [cmgriffing/raidy-or-not-next#2]
The Button for Logout is cut.      
     
Windows 11, Chrome without Extensions.
     
![image](https://user-images.githubusercontent.com/105616222/168505381-6f803df1-5bd9-4a49-b7e2-bf90e444c8e9.png)
![image](https://user-images.githubusercontent.com/105616222/168505313-e2458b2e-86bf-4ef1-a1b5-571ab91cbe0a.png)

**Comment by cmgriffing** [comment]
This is fixed now. It ended up being a z-index issue.
